In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

In [4]:
data = pd.read_csv('data_used/Berlin Traffic Accident 2019-2021 cleaned.csv')

In [5]:
data

,Unnamed: 0,id,city,district,year,month,hour,weekday,injury_level,collision,...,light_conditions,bicycle,car,pedestrian,motorbike,truck,other_vehicle,road_conditions,longitude,latitude
0,0,49090,11,12,2019,1,13,6,3,5,...,0,1,1,0,0,0,0,1,13.341460,52.586090
1,1,49091,11,3,2019,1,9,5,3,5,...,0,1,1,0,0,0,0,0,13.413560,52.558620
2,2,49093,11,12,2019,3,21,6,3,0,...,2,1,0,0,0,0,0,0,13.360340,52.571590
3,3,49096,11,6,2019,1,7,6,2,6,...,1,0,1,1,0,0,0,1,13.217770,52.428250
4,4,49097,11,7,2019,2,15,3,3,2,...,0,0,1,0,0,0,0,0,13.360070,52.474210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36462,36462,112174,11,4,2021,3,16,4,3,6,...,0,0,1,1,0,0,0,1,13.296345,52.511008
36463,36463,111541,11,4,2021,1,1,6,3,9,...,2,0,1,0,0,0,0,0,13.289496,52.493813
36464,36464,110370,11,3,2021,1,20,1,3,3,...,2,0,1,0,0,0,0,1,13.423095,52.527534
36465,36465,109998,11,7,2021,1,14,7,3,2,...,0,0,1,0,0,0,0,1,13.359259,52.474367
36466,36466,109753,11,12,2021,1,14,2,3,5,...,0,0,1,0,0,0,1,1,13.312868,52.622461

In [ ]:
data.drop(["id", "city"], axis=1, inplace=True)

In [11]:
# Drop rows with missing target values
data.dropna(subset=["injury_level"], inplace=True)

# Split data into features (X) and target variable (y)
X = data.drop("injury_level", axis=1)
y = data["injury_level"]

# Split data into training and testing sets with a smaller test size
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

# Train a Random Forest regressor
regressor = RandomForestRegressor(n_estimators=100, random_state=42)
regressor.fit(X_train, y_train)

# Make predictions on the test set
y_pred = regressor.predict(X_test)

# Evaluate the model using R^2 score
r2 = r2_score(y_test, y_pred)
print("R^2 Score:", r2)

R^2 Score: -0.006116340617443594

In [7]:
data

,Unnamed: 0,id,city,district,year,month,hour,weekday,injury_level,collision,...,light_conditions,bicycle,car,pedestrian,motorbike,truck,other_vehicle,road_conditions,longitude,latitude
0,0,49090,11,12,2019,1,13,6,3,5,...,0,1,1,0,0,0,0,1,13.341460,52.586090
1,1,49091,11,3,2019,1,9,5,3,5,...,0,1,1,0,0,0,0,0,13.413560,52.558620
2,2,49093,11,12,2019,3,21,6,3,0,...,2,1,0,0,0,0,0,0,13.360340,52.571590
3,3,49096,11,6,2019,1,7,6,2,6,...,1,0,1,1,0,0,0,1,13.217770,52.428250
4,4,49097,11,7,2019,2,15,3,3,2,...,0,0,1,0,0,0,0,0,13.360070,52.474210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36462,36462,112174,11,4,2021,3,16,4,3,6,...,0,0,1,1,0,0,0,1,13.296345,52.511008
36463,36463,111541,11,4,2021,1,1,6,3,9,...,2,0,1,0,0,0,0,0,13.289496,52.493813
36464,36464,110370,11,3,2021,1,20,1,3,3,...,2,0,1,0,0,0,0,1,13.423095,52.527534
36465,36465,109998,11,7,2021,1,14,7,3,2,...,0,0,1,0,0,0,0,1,13.359259,52.474367
36466,36466,109753,11,12,2021,1,14,2,3,5,...,0,0,1,0,0,0,1,1,13.312868,52.622461

In [12]:
# Feature Engineering (example: creating interaction terms)
data['interaction_term'] = data['month'] * data['hour']

# Update X and y
X = data.drop("injury_level", axis=1)
y = data["injury_level"]

# Hyperparameter Tuning
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}
grid_search = GridSearchCV(RandomForestRegressor(random_state=42), param_grid, cv=5)
grid_search.fit(X, y)

# Evaluate the model using R^2 score
r2 = grid_search.best_score_
print("Best R^2 Score:", r2)

NameError: name 'GridSearchCV' is not defined

In [ ]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

# Drop rows with missing target values
data.dropna(subset=["injury_level"], inplace=True)

# Split data into features (X) and target variable (y)
X = data.drop("injury_level", axis=1)
y = data["injury_level"]

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Hyperparameter tuning
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}
grid_search = GridSearchCV(RandomForestRegressor(random_state=42), param_grid, cv=5)
grid_search.fit(X_train, y_train)

# Best parameters found during grid search
print("Best Parameters:", grid_search.best_params_)

# Make predictions on the test set
y_pred = grid_search.predict(X_test)

# Evaluate the model using R^2 score
r2 = r2_score(y_test, y_pred)
print("R^2 Score:", r2)